### ISSUE TITLE
Team display page

### ISSUE THREAD

**Issue by GabrielAdward** [Gabriel-Albin-Erik-Rikard/Football-ManagerAndroidDevelopment#14]
Create Following pages:

Create a Teams page where all teams connected to the account are displayed
Create a specific team page where both staff and players are displayed 
Create a player-view to display information about specific player 
Create a staff-view to display information about specific staff

**Comment by Hellberg95** [comment]
Typ klar, ska fundera lite på design bara. Har inget koppling mellan account-group/team än dock
